services:
    ts:
      tty: true
      init: true
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./:/app:cache
        - node_modules:/app/node_modules
      environment:
        NODE_ENV: development

volumes:
  node_modules:
