services:
    ts:
      tty: true
      init: true
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./:/app:cache
      environment:
        NODE_ENV: development
